apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: roboshop
  labels:
   environment: development
   project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:9
    ports:
    - containerPort: 8080
    command: ["sleep","3000"]