apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
   environment: development
   project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: alpine
    image: apline:latest
    ports:
    - containerPort: 8080