apiVersion: v1
kind: Pod
metadata:
   name: nginx
   namespace: roboshop
   labels:
    environment: development
    project: roboshop
spec:
 containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
    resources:
      requests:
        cpu: "10m" #1000 milli cores is 1cpu
        memory: "10Mi"
      limits:
        cpu: "20m"
        memory: "10Mi"