apiVersion: v1
kind: Pod
metadata:
   labels:
    environment: development
    project: roboshop
spec:
 containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "10m"
        memory: "10mi"
      limits:
        cpu: "20m"
        memory: "10mi"