apiVersion: v1
kind: Pod
metadata:
   name: nginx
   namespace: roboshop
   labels:
    environment: development
    project: roboshop
spec:
 containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
    resources:
      requests:
        cpu: "10m" #1000 milli cores is 1cpu
        memory: "10Mi"
      limits:
        cpu: "20m"
        memory: "10Mi"


#containers - Is a list object, contains list of containers.
#ports: parallel to image
#resource: parallel to image
#cpu and memory are string values.
#Mi is for memory
#1000 milli core is 1 CPU
