apiVersion: v1 
kind: Pod 
metadata: 
 name: empty-dir-demo
 namespace: default
spec:
 containers: 
 - name: nginx
   image: nginx
   volumeMounts:
   - name: nginx-logs
     mountPath: /var/log/nginx
 - name: almalinux
   image: almalinx:9
   volumeMounts:
   - name: nginx-logs
     mountPath: /mnt/nginx-logs
     readOnly: true
   command: ["sleep","10000"]
 volumes:
 - name: nginx-logs 
   emptyDir:
    sizeLimit: 100Mi



  