#volumes: Indentation should be parallel to containers
#volumes: it is a list object, list of volumes
#volumeMounts: It is list of volume mounts
#volumeMounts: it should be parallel to image

apiVersion: v1 
kind: Pod 
metadata: 
 name: empty-dir-demo
 namespace: default
spec:
 containers: 
 - name: nginx
   image: nginx
   volumeMounts:
   - name: nginx-logs
     mountPath: /var/log/nginx
 - name: almalinux
   image: almalinux:9
   volumeMounts:
   - name: nginx-logs
     mountPath: /mnt/nginx-logs
     readOnly: true
   command: ["sleep","10000"]
 volumes:
 - name: nginx-logs 
   emptyDir:
    sizeLimit: 100Mi



  
