# Volumebindmode doesn't apply to EFS, it is by default immediate no "waitforfirstconsumer".
# Not just that EFS is a shared volume and not a volume attached storage like EBS.
# You need to have the EFS created on each AZ, so that you can mount the EFS on nodes across AZ.
# This is the storage that supports the accessMode ReadWriteMany

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: roboshop-efs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1 
kind: Pod 
metadata:
 name: nginx
spec:
 containers:
 - name: nginx
   image: nginx
   volumeMounts:
   - name: nginx-html
     mountPath: /usr/share/nginx/html
 volumes:
 - name: nginx-html
   persistentVolumeClaim: 
    claimName: efs-dynamic
