apiVersion: apps/v1 
kind: Deployment #Type of resource
metadata:
 name: headless-demo #Name of the resource
 labels: #Resource tags for filtering and identification
  purpose: headless-svc-demo 
  project: roboshop
spec:            #Specfications of the containers
 replicas: 4
 selector: 
  matchLabels:
   purpose: headless-svc-demo 
   project: roboshop
 template: 
  metadata:
    labels: 
     purpose: headless-svc-demo
     project: roboshop 
  spec:
   containers: 
   - name: nginx           #Name and image of the container
     image: nginx:latest
---
apiVersion: v1 
kind: Service  #Resource type service
metadata: 
 name: nginx
spec:
 selector: #Filter the pods based on these selectors
  purpose: headless-svc-demo  
  project: roboshop
 ports:
 - protocal: TCP 
   port: 80 #Service port
   targetPort: 80 #Container port
