# Selector doesn't include matchLables
# type: type of service
# Ports: is a list of objects
# Need to specify protocal
apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
 selector:
  project: roboshop
  component: frontend
  environment: dev
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # container port
