apiVersion: v1
kind: Service
metadata:
  name:  nginx-lb # Creates classic loadbalancer
spec:
 selector:
  project: roboshop
  component: frontend
  environment: dev
  purpose: loadbalancer #EKS nodeport rance 30000-32767
 type: LoadBalancer #Loadbalancer automtically adds rules in security group.
 ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port
    nodePort: 30007