apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
 selector:
  project: roboshop
  component: frontend
  environment: dev
  purpose: node-port
 type: NodePort # it we don't specify it will consider as cluster ip
 ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 # container port