apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
 selector:
  project: roboshop
  component: frontend
  environment: dev
 ports:
  - protocal: TCP
    port: 80
    targetPort: 80 # container port
