apiVersion: apps/v1 
kind: Deployment #Type of resource
metadata:
 name: headless-demo #Name of the resource
 labels: #Resource tags for filtering and identification
  purpose: headless-svc-demo 
  project: roboshop
spec:            #Specfications of the containers
 replicas: 4
 selector: 
  matchLabels:
   purpose: headless-svc-demo 
   project: roboshop
 template: 
  metadata:
    labels: 
     purpose: headless-svc-demo
     project: roboshop 
  spec:
   containers: 
   - name: nginx           #Name and image of the container
     image: nginx:latest
---
apiVersion: v1 
kind: Service  #Resource type service
metadata: 
 name: nginx
spec:
  selector: #Filter the pods based on these selectors
   purpose: headless-svc-demo  
   project: roboshop
  ports:
  - protocol: TCP 
    port: 80 #Service port
    targetPort: 80 #Container port

#Access to one of the pod and install nslookup
#apt update
#apt install dnsutils
#Do nslookup <servicename> it will retrun IP of the service for a normal service.
#Example -> nslookup nginx
#;; Got recursion not available from 10.100.0.10
#Server:         10.100.0.10
#Address:        10.100.0.10#53

#Name:   nginx.default.svc.cluster.local
#Address: 10.100.78.100
#;; Got recursion not available from 10.100.0.10

#Now create below headless service with clusterIP set to None
#Do the same nslookup of this service it will return the IPs of the pods.
#Used for peer discovery or to find available members of the DB/STS cluster.
---
apiVersion: v1 
kind: Service  #Resource type service
metadata: 
 name: nginx-headless #If cluster IP is none, it is called as headless service
spec:
  clusterIP: None
  selector: #Filter the pods based on these selectors
   purpose: headless-svc-demo  
   project: roboshop
  ports:
  - protocol: TCP 
    port: 80 #Service port
    targetPort: 80 #Container port