#envFrom: it is a list of objects
# - secretRef is the list
# K8s decodes the base64 values and addes it to environment variables
```
apiVersion: v1
kind: Pod
metadata:
 name: secret
spec:
 containers:
 - name: nginx
   image: nginx
   envFrom:
   - secretRef:
      name: pod-secret
