apiVersion: v1
kind: Pod
metadata:
 name: secret
spec:
 containers:
 - name: nginx
   image: nginx
   envFrom:
   - secretRef:
      name: pod-secret
# K8s will decode this secret, attach to pod as env variable
