#There is no Spec in secret object
# You have data, type.
# input to data is key and value pair.
apiVersion: v1
kind: Secret
metadata: 
  name: pod-secret
type: Opaque
data: 
 username: "YWRtaW4K"
 password: "cm9ibzEyMwo="
